// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsKiZqMqW0AowLJO1bpd2-y0XqHtRGz5k',
    appId: '1:961604103195:web:28719dff7f2caa9b079cbe',
    messagingSenderId: '961604103195',
    projectId: 'realchattingapp-a0077',
    authDomain: 'realchattingapp-a0077.firebaseapp.com',
    storageBucket: 'realchattingapp-a0077.firebasestorage.app',
    measurementId: 'G-C2PC6RTSRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ3OgvjQJNF4Hf7kPegWS3M2CwPrwR7ok',
    appId: '1:961604103195:android:8c9934453fd1c8fd079cbe',
    messagingSenderId: '961604103195',
    projectId: 'realchattingapp-a0077',
    storageBucket: 'realchattingapp-a0077.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMomYdHaLsgbJz-NFefDOFMXYWWt6hWrs',
    appId: '1:961604103195:ios:6999a17c221b554b079cbe',
    messagingSenderId: '961604103195',
    projectId: 'realchattingapp-a0077',
    storageBucket: 'realchattingapp-a0077.firebasestorage.app',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMomYdHaLsgbJz-NFefDOFMXYWWt6hWrs',
    appId: '1:961604103195:ios:6999a17c221b554b079cbe',
    messagingSenderId: '961604103195',
    projectId: 'realchattingapp-a0077',
    storageBucket: 'realchattingapp-a0077.firebasestorage.app',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsKiZqMqW0AowLJO1bpd2-y0XqHtRGz5k',
    appId: '1:961604103195:web:be8dce2e21a78f50079cbe',
    messagingSenderId: '961604103195',
    projectId: 'realchattingapp-a0077',
    authDomain: 'realchattingapp-a0077.firebaseapp.com',
    storageBucket: 'realchattingapp-a0077.firebasestorage.app',
    measurementId: 'G-F71T5P9RLS',
  );
}
